import type { Trip, Signals } from "./types";

const s = (
  preferenceMatch: number,
  popularity: number,
  budgetFit: number,
  scheduleFit: number,
  historyMatch: number | null = null,
): Signals => ({ preferenceMatch, popularity, budgetFit, scheduleFit, historyMatch });

export const TRAVELLER_COLORS = ["#f472b6", "#22d3ee", "#c084fc", "#fb923c", "#facc15", "#4ade80"];

export const INTEREST_OPTIONS = [
  "Culture",
  "Food",
  "Shopping",
  "Nightlife",
  "Nature",
  "Relaxation",
  "History",
  "Photography",
];

export function buildDemoTrip(): Trip {
  const ids = { alice: "t1", bob: "t2", charlie: "t3", david: "t4" };
  const all = [ids.alice, ids.bob, ids.charlie, ids.david];

  return {
    name: "Japan Adventure",
    budgetMode: "shared",
    groupBudget: 5000,
    displayCurrency: "MYR",
    days: 5,
    startDate: "2026-04-06",
    groupNote:
      "Your plan leans into Japanese culture and food while keeping walking moderate for Alice. Shopping is grouped in the afternoons, and Charlie gets extra culture and nature options on days with parallel activities.",
    travellers: [
      {
        id: ids.alice,
        name: "Alice",
        color: TRAVELLER_COLORS[0],
        budget: 1000,
        prefs: {
          budget: "Medium",
          interests: ["Shopping", "Culture"],
          pace: "Balanced",
          walking: "Low",
          intensity: "Low",
          food: ["Japanese"],
          mustDo: ["Shibuya"],
          avoid: ["Long hikes"],
          preferredTimes: "Afternoons",
          accessibility: "Prefers minimal stairs",
        },
      },
      {
        id: ids.bob,
        name: "Bob",
        color: TRAVELLER_COLORS[1],
        budget: 2000,
        prefs: {
          budget: "High",
          interests: ["Food", "Nightlife"],
          pace: "Packed",
          walking: "Medium",
          intensity: "High",
          food: ["Seafood", "Street food"],
          mustDo: ["Tsukiji"],
          avoid: ["Museums"],
          preferredTimes: "Evenings",
          accessibility: "",
        },
      },
      {
        id: ids.charlie,
        name: "Charlie",
        color: TRAVELLER_COLORS[2],
        budget: 1500,
        prefs: {
          budget: "Low",
          interests: ["Nature", "Culture"],
          pace: "Balanced",
          walking: "High",
          intensity: "Medium",
          food: ["Vegetarian-friendly"],
          mustDo: ["Meiji Shrine"],
          avoid: [],
          preferredTimes: "Mornings",
          accessibility: "",
        },
      },
      {
        id: ids.david,
        name: "David",
        color: TRAVELLER_COLORS[3],
        budget: 800,
        prefs: {
          budget: "Low",
          interests: ["Relaxation", "Photography"],
          pace: "Relaxed",
          walking: "Medium",
          intensity: "Low",
          food: ["Japanese"],
          mustDo: [],
          avoid: ["Crowded nightlife"],
          preferredTimes: "Flexible",
          accessibility: "",
        },
      },
    ],
    subgroups: [
      { id: "g1", name: "Shoppers", members: [ids.alice, ids.bob] },
      { id: "g2", name: "Explorers", members: [ids.charlie, ids.david] },
    ],
    destinations: [
      {
        id: "d1",
        city: "Tokyo",
        country: "Japan",
        currency: "JPY",
        arrival: "Apr 6, 15:00",
        departure: "Apr 8, 09:00",
        dayStart: 0,
        dayEnd: 1,
      },
      {
        id: "d2",
        city: "Kyoto",
        country: "Japan",
        currency: "JPY",
        arrival: "Apr 8, 11:45",
        departure: "Apr 10, 09:30",
        dayStart: 2,
        dayEnd: 3,
      },
      {
        id: "d3",
        city: "Osaka",
        country: "Japan",
        currency: "JPY",
        arrival: "Apr 10, 10:00",
        departure: "Apr 11, 12:00",
        dayStart: 4,
        dayEnd: 4,
      },
    ],
    legs: [
      {
        id: "l1",
        from: "Tokyo",
        to: "Kyoto",
        dayIndex: 2,
        type: "High-speed rail",
        departure: "09:30",
        arrival: "11:45",
        durationMin: 135,
        cost: { amount: 14000, currency: "JPY" },
        participants: all,
      },
      {
        id: "l2",
        from: "Kyoto",
        to: "Osaka",
        dayIndex: 4,
        type: "Train",
        departure: "09:30",
        arrival: "10:00",
        durationMin: 30,
        cost: { amount: 600, currency: "JPY" },
        participants: all,
      },
    ],
    accommodations: [
      {
        id: "a1",
        destinationId: "d1",
        name: "Shinjuku Granbell Hotel",
        location: "Shinjuku, Tokyo",
        checkIn: "Apr 6",
        checkOut: "Apr 8",
        nights: 2,
        room: "2 twin rooms",
        costPerNight: { amount: 18000, currency: "JPY" },
        participants: all,
      },
      {
        id: "a2",
        destinationId: "d2",
        name: "Kyoto Machiya Stay",
        location: "Gion, Kyoto",
        checkIn: "Apr 8",
        checkOut: "Apr 10",
        nights: 2,
        room: "Whole townhouse",
        costPerNight: { amount: 15000, currency: "JPY" },
        participants: all,
      },
      {
        id: "a3",
        destinationId: "d3",
        name: "Namba Oriental Hotel",
        location: "Namba, Osaka",
        checkIn: "Apr 10",
        checkOut: "Apr 11",
        nights: 1,
        room: "2 twin rooms",
        costPerNight: { amount: 16000, currency: "JPY" },
        participants: all,
      },
    ],
    weather: [
      { dayIndex: 0, city: "Tokyo", tempC: 21, condition: "Sunny" },
      {
        dayIndex: 1,
        city: "Tokyo",
        tempC: 22,
        condition: "Rain",
        note: "Rain expected in Tokyo around 14:00.",
        affectsActivityId: "ac6",
      },
      { dayIndex: 2, city: "Kyoto", tempC: 19, condition: "Cloudy" },
      { dayIndex: 3, city: "Kyoto", tempC: 23, condition: "Sunny" },
      { dayIndex: 4, city: "Osaka", tempC: 24, condition: "Sunny" },
    ],
    manualExpenses: [],
    activities: [
      // Day 0 — Tokyo
      {
        id: "ac1",
        dayIndex: 0,
        startTime: "09:00",
        endTime: "12:00",
        name: "Tsukiji Outer Market",
        location: "Tsukiji",
        city: "Tokyo",
        country: "Japan",
        description: "Fresh sushi breakfast and street-food stalls in the historic outer market.",
        participants: all,
        activityCost: { amount: 3000, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 200, currency: "JPY" },
        travelDuration: 20,
        walkingDuration: 40,
        walkingLevel: "Medium",
        activityType: "Food",
        signals: s(92, 96, 88, 95, 82),
        reason: "Matches Bob's must-do and the group's strong food preference. Central and easy to reach.",
        inspirationLinks: [
          { label: "Watch food tour", url: "https://www.youtube.com/watch?v=CB4XX8xIVGU" },
          { label: "See on TikTok", url: "https://www.tiktok.com/@tokyo.eats/video/7248300000000000000" },
        ],
        locked: true,
        alternatives: [],
      },
      {
        id: "ac2",
        dayIndex: 0,
        startTime: "14:00",
        endTime: "17:00",
        name: "Shibuya Shopping",
        location: "Shibuya",
        city: "Tokyo",
        country: "Japan",
        description: "Fashion and lifestyle shopping around Shibuya Scramble and Miyashita Park.",
        participants: [ids.alice, ids.bob],
        activityCost: { amount: 8000, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 300, currency: "JPY" },
        travelDuration: 25,
        walkingDuration: 30,
        walkingLevel: "Low",
        activityType: "Shopping",
        signals: s(90, 89, 72, 90),
        reason: "Matches Alice and Bob's shopping preference and stays within their current budgets.",
        inspirationLinks: [
          { label: "Shibuya walk video", url: "https://www.youtube.com/watch?v=0nTO4zSEpOs" },
        ],
        locked: false,
        alternatives: [
          {
            id: "alt-ac2-1",
            name: "Shibuya Sky",
            location: "Shibuya Scramble Square",
            cost: { amount: 2500, currency: "JPY" },
            walking: "Low",
            activityType: "Sightseeing",
            tags: ["Fits budget", "Popular"],
            reason: "Costs less than the original, keeps walking low, and matches Alice and Bob.",
            signals: s(84, 94, 96, 88),
          },
          {
            id: "alt-ac2-2",
            name: "Harajuku Takeshita Walk",
            location: "Harajuku",
            cost: { amount: 0, currency: "JPY" },
            walking: "Medium",
            activityType: "Shopping",
            tags: ["Budget friendly"],
            reason: "Free browsing that still fits the shopping interest.",
            signals: s(78, 82, 100, 84),
          },
        ],
      },
      {
        id: "ac3",
        dayIndex: 0,
        startTime: "14:00",
        endTime: "16:00",
        name: "Tokyo National Museum",
        location: "Ueno",
        city: "Tokyo",
        country: "Japan",
        description: "Japan's largest collection of cultural artefacts, indoors and step-free.",
        participants: [ids.charlie],
        activityCost: { amount: 1000, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 200, currency: "JPY" },
        travelDuration: 30,
        walkingDuration: 25,
        walkingLevel: "Low",
        activityType: "Culture",
        signals: s(88, 80, 94, 86, 70),
        reason: "Matches Charlie's culture interest while the shoppers are in Shibuya.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac4",
        dayIndex: 0,
        startTime: "16:00",
        endTime: "18:00",
        name: "Free time",
        location: "Shinjuku",
        city: "Tokyo",
        country: "Japan",
        description: "Unscheduled time to rest or explore independently near the hotel.",
        participants: [ids.david],
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 15,
        walkingLevel: "Low",
        activityType: "Relaxation",
        signals: s(80, 60, 100, 90),
        reason: "Matches David's relaxed pace and keeps his budget low.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac5",
        dayIndex: 0,
        startTime: "18:30",
        endTime: "20:00",
        name: "Izakaya Dinner",
        location: "Shinjuku",
        city: "Tokyo",
        country: "Japan",
        description: "Group dinner at a lively izakaya with shared plates.",
        participants: all,
        activityCost: { amount: 6000, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 10,
        walkingLevel: "Low",
        activityType: "Food",
        signals: s(94, 88, 84, 92),
        reason: "Shared meal that fits everyone's Japanese food preference.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      // Day 1 — Tokyo
      {
        id: "ac_meiji",
        dayIndex: 1,
        startTime: "09:30",
        endTime: "11:30",
        name: "Meiji Shrine",
        location: "Harajuku",
        city: "Tokyo",
        country: "Japan",
        description: "Forested shrine walk in the heart of the city.",
        participants: all,
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 200, currency: "JPY" },
        travelDuration: 20,
        walkingDuration: 50,
        walkingLevel: "Medium",
        activityType: "Culture",
        signals: s(90, 91, 100, 88),
        reason: "Charlie's must-do, culturally rich, and free for everyone.",
        inspirationLinks: [],
        locked: true,
        alternatives: [],
      },
      {
        id: "ac6",
        dayIndex: 1,
        startTime: "14:00",
        endTime: "16:00",
        name: "Odaiba Seaside Park",
        location: "Odaiba",
        city: "Tokyo",
        country: "Japan",
        description: "Waterfront views, the Rainbow Bridge and outdoor promenades.",
        participants: all,
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Train",
        transportCost: { amount: 500, currency: "JPY" },
        travelDuration: 35,
        walkingDuration: 60,
        walkingLevel: "High",
        activityType: "Nature",
        signals: s(76, 78, 100, 82),
        reason: "Outdoor break matching Charlie and David's nature and photography interests.",
        inspirationLinks: [],
        locked: false,
        alternatives: [
          {
            id: "alt-ac6-1",
            name: "teamLab Planets",
            location: "Toyosu",
            cost: { amount: 3800, currency: "JPY" },
            walking: "Low",
            activityType: "Culture",
            tags: ["Indoor", "Popular"],
            reason: "Fully indoor, avoids the rain, and keeps the photography interest with lower walking.",
            signals: s(86, 95, 78, 90),
          },
          {
            id: "alt-ac6-2",
            name: "Tokyo National Museum",
            location: "Ueno",
            cost: { amount: 1000, currency: "JPY" },
            walking: "Low",
            activityType: "Culture",
            tags: ["Indoor", "Budget friendly"],
            reason: "Indoor culture that preserves the group's interest and stays cheap.",
            signals: s(82, 80, 96, 84),
          },
        ],
      },
      {
        id: "ac7",
        dayIndex: 1,
        startTime: "19:30",
        endTime: "22:00",
        name: "Shinjuku Nightlife",
        location: "Golden Gai, Shinjuku",
        city: "Tokyo",
        country: "Japan",
        description: "Tiny bars and late-night eats in Golden Gai.",
        participants: [ids.bob],
        activityCost: { amount: 5000, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 20,
        walkingLevel: "Medium",
        activityType: "Nightlife",
        signals: s(93, 84, 66, 80),
        reason: "Matches Bob's nightlife preference; optional for others who prefer to rest.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      // Day 2 — Kyoto
      {
        id: "ac8",
        dayIndex: 2,
        startTime: "13:00",
        endTime: "15:00",
        name: "Fushimi Inari Shrine",
        location: "Fushimi",
        city: "Kyoto",
        country: "Japan",
        description: "Thousands of vermilion torii gates winding up the mountain.",
        participants: all,
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Train",
        transportCost: { amount: 300, currency: "JPY" },
        travelDuration: 20,
        walkingDuration: 70,
        walkingLevel: "High",
        activityType: "Culture",
        signals: s(89, 97, 100, 85),
        reason: "Iconic and free; a lighter loop keeps it manageable for Alice.",
        inspirationLinks: [{ label: "See on Instagram", url: "https://www.instagram.com/explore/tags/fushimiinari/" }],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac9",
        dayIndex: 2,
        startTime: "16:00",
        endTime: "17:30",
        name: "Nishiki Market",
        location: "Central Kyoto",
        city: "Kyoto",
        country: "Japan",
        description: "Covered market known as Kyoto's kitchen.",
        participants: [ids.alice, ids.bob, ids.david],
        activityCost: { amount: 2500, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 30,
        walkingLevel: "Low",
        activityType: "Food",
        signals: s(85, 88, 90, 88),
        reason: "Food and light shopping; step-free and central.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      // Day 3 — Kyoto (parallel afternoon)
      {
        id: "ac10",
        dayIndex: 3,
        startTime: "09:00",
        endTime: "11:00",
        name: "Arashiyama Bamboo Grove",
        location: "Arashiyama",
        city: "Kyoto",
        country: "Japan",
        description: "Walk through the towering bamboo forest early to beat crowds.",
        participants: all,
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Train",
        transportCost: { amount: 400, currency: "JPY" },
        travelDuration: 30,
        walkingDuration: 50,
        walkingLevel: "Medium",
        activityType: "Nature",
        signals: s(88, 95, 100, 86, 76),
        reason: "Nature highlight for Charlie and David; scenic and free.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac11",
        dayIndex: 3,
        startTime: "15:00",
        endTime: "17:30",
        name: "Kyoto Handicraft Shopping",
        location: "Higashiyama",
        city: "Kyoto",
        country: "Japan",
        description: "Ceramics, textiles and craft studios.",
        participants: [ids.alice, ids.bob],
        activityCost: { amount: 6000, currency: "JPY" },
        transportType: "Bus",
        transportCost: { amount: 230, currency: "JPY" },
        travelDuration: 25,
        walkingDuration: 25,
        walkingLevel: "Low",
        activityType: "Shopping",
        signals: s(87, 76, 74, 85),
        reason: "Shopping for Alice and Bob while the others do a cultural walk.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac12",
        dayIndex: 3,
        startTime: "15:00",
        endTime: "17:00",
        name: "Gion Cultural Walk",
        location: "Gion",
        city: "Kyoto",
        country: "Japan",
        description: "Historic geisha district and machiya streets.",
        participants: [ids.charlie, ids.david],
        activityCost: { amount: 0, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 45,
        walkingLevel: "Medium",
        activityType: "Culture",
        signals: s(90, 84, 100, 88, 74),
        reason: "Culture and photography for Charlie and David, running parallel to shopping.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      // Day 4 — Osaka
      {
        id: "ac13",
        dayIndex: 4,
        startTime: "11:00",
        endTime: "13:00",
        name: "Osaka Castle",
        location: "Chuo Ward",
        city: "Osaka",
        country: "Japan",
        description: "Iconic castle and surrounding park.",
        participants: all,
        activityCost: { amount: 600, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 280, currency: "JPY" },
        travelDuration: 25,
        walkingDuration: 40,
        walkingLevel: "Medium",
        activityType: "History",
        signals: s(85, 90, 96, 88),
        reason: "History highlight, affordable, and central to Osaka.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac14",
        dayIndex: 4,
        startTime: "14:30",
        endTime: "17:00",
        name: "Dotonbori Food Tour",
        location: "Dotonbori",
        city: "Osaka",
        country: "Japan",
        description: "Takoyaki, okonomiyaki and neon canals.",
        participants: all,
        activityCost: { amount: 5000, currency: "JPY" },
        transportType: "Metro",
        transportCost: { amount: 240, currency: "JPY" },
        travelDuration: 20,
        walkingDuration: 45,
        walkingLevel: "Medium",
        activityType: "Food",
        signals: s(93, 94, 82, 90),
        reason: "Street-food finale matching Bob's food interest and the group.",
        inspirationLinks: [
          { label: "Dotonbori night walk", url: "https://www.youtube.com/watch?v=2TZ0Cbz-uMk" },
          { label: "See on TikTok", url: "https://www.tiktok.com/@osaka.food/video/7311200000000000000" },
        ],
        locked: false,
        alternatives: [],
      },
      {
        id: "ac15",
        dayIndex: 4,
        startTime: "19:00",
        endTime: "21:00",
        name: "Farewell Dinner",
        location: "Namba",
        city: "Osaka",
        country: "Japan",
        description: "Final group dinner to close the trip.",
        participants: all,
        activityCost: { amount: 8000, currency: "JPY" },
        transportType: "Walking",
        travelDuration: 0,
        walkingDuration: 10,
        walkingLevel: "Low",
        activityType: "Food",
        signals: s(90, 82, 76, 90),
        reason: "A memorable close-out meal for everyone.",
        inspirationLinks: [],
        locked: false,
        alternatives: [],
      },
    ],
  };
}
